environment:
  expat: 'C:\Program Files (x86)\Expat 2.2.5'
  GENERATOR: Visual Studio 15 2017
  PLATFORM: Win32
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
  - cmd: choco install wget
  - cmd: wget https://github.com/libexpat/libexpat/releases/download/R_2_2_5/expat-win32bin-2.2.5.exe --output-document=C:\expat.exe
  - cmd: C:\expat.exe /silent

configuration: Release

build:
  project: Src\Win32\Dasher.sln
