install:
  - cmd: choco install wget
  - cmd: wget https://github.com/libexpat/libexpat/releases/download/R_2_2_5/expat-win32bin-2.2.5.exe --output-document=C:\expat.exe
  - cmd: C:\expat.exe /silent
  - cmd: msbuild "Src\Win32\Dasher.sln"
  - cmd: if exist Src\Win32\Target\Release\Dasher.exe appveyor exit
  - cmd: if not exist Src\Win32\Target\Release\Dasher.exe exit 1 

configuration: Release

environment:
  expat: 'C:\Program Files (x86)\Expat 2.2.5'
  GENERATOR: Visual Studio 15 2017
  PLATFORM: Win32
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
build: off
