//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Dasher.rc
//
#define IDC_MYICON                      2
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    105
#define IDM_ABOUT                       106
#define IDS_FILE_SAVE                   107
#define IDM_EXIT                        108
#define IDS_OPTIONS_PREFS               108
#define IDS_FILE_OPEN                   109
#define IDS_HELLO                       110
#define IDS_FILE_NEW                    111
#define IDI_DASHER                      112
#define IDS_EDIT_CUT                    113
#define IDI_SMALL                       114
#define IDS_EDIT_COPY                   115
#define IDC_DASHER                      116
#define IDS_EDIT_PASTE                  117
#define IDS_EDIT_COPY_ALL               119
#define IDS_PREFS_TITLE                 140
#define IDS_PREFS_CONTROL               141
#define IDD_ALPHABETPAGE                141
#define IDS_PREFS_VIEW                  144
#define IDS_QUERY_SAVE_CHANGES          145
#define IDS_PREFS_ALPHABET              146
#define IDS_UNTITLED_FILE               147
#define IDB_COPY_ALL_LARGE_COLOR        148
#define IDS_PREFS_COLOUR                148
#define IDS_UNSAVED_CHANGES             149
#define IDS_PREFS_LM                    151
#define IDS_ERR_SOCKET_TITLE            156
#define IDD_CONTROLPAGE                 168
#define ID_OPTIONS_PREFS                169
#define IDD_APPEARANCEPAGE              178
#define IDD_APPPAGE                     179
#define IDD_MODULESETTINGS              180
#define IDD_STATUSBAR                   182
#define IDC_INPUT_LIST                  1008
#define IDC_CONTROL_LIST                1009
#define IDC_ALPHABETS                   1010
#define IDC_DFONT_BUTTON                1014
#define IDC_EFONT_BUTTON                1016
#define IDC_BUTTON_PREFS                1018
#define IDC_BUTTON_PREFS2               1019
#define IDC_THICKLINE                   1020
#define IDC_COPYONSTOP                  1020
#define IDC_MIRROR_LAYOUT               1021
#define IDC_RESET_ON_FOCUS_CHANGE       1022
#define IDC_SPACE                       1036
#define IDC_UNIFORMVAL                  1040
#define IDC_CHECK3                      1071
#define IDC_LEFT                        1071
#define IDC_WINDOWPAUSE                 1088
#define IDC_MOUSEPOS                    1089
#define IDC_OUTLINE                     1091
#define IDC_TIMESTAMP                   1092
#define IDC_CONFIRM_UNSAVED             1093
#define IDC_DRAWMOUSE                   1094
#define IDC_DRAWMOUSELINE               1097
#define IDC_COLOURSCHEME                1098
#define IDC_COLOURS                     1099
#define IDC_UNIFORMSLIDER               1100
#define IDC_CHECK1                      1112
#define IDC_OR_CUSTOM                   1112
#define IDC_CHECK2                      1113
#define IDC_ADAPTIVE                    1114
#define IDC_LM_PPM                      1115
#define IDC_LM_WORD                     1116
#define IDC_LM_MIXTURE                  1117
#define IDC_LM_JAPANESE                 1118
#define IDC_AUTOSPEED                   1119
#define IDC_SPEEDSLIDER                 1120
#define IDC_SPEEDVAL                    1121
#define IDC_STYLE_STANDALONE            1122
#define IDC_STYLE_COMPOSITION           1123
#define IDC_STYLE_DIRECT                1124
#define IDC_MOUSEPOS_STYLE              1144
#define IDC_AUTOCALIBRATE               1145
#define IDC_CONTROLMODE                 1146
#define IDC_OR_DEFAULT                  1148
#define IDC_OR_LR                       1149
#define IDC_OR_RL                       1150
#define IDC_OR_TB                       1151
#define IDC_OR_BT                       1152
#define IDC_FONT_SMALL                  1153
#define IDC_FONT_LARGE                  1154
#define IDC_FONT_VLARGE                 1155
#define IDC_CHECK4                      1156
#define IDC_CHECK5                      1157
#define IDC_CONTROLBOXES                1160
#define IDC_FILE_ENCODING               1161
#define IDC_SPEED_EDIT                  1163
#define IDC_SPEED_SPIN                  1164
#define IDC_ALPHABET_COMBO              1166
#define ID_EDIT_SELECTALL               32775
#define ID_HELP_CONTENTS                32776
#define ID_EDIT_COPY_ALL                32798
#define ID_IMPORT_TRAINFILE             32799
#define ID_FILE_APPEND                  32800
#define ID_FILE_SAVE_AS                 32801
#define ID_FILE_SAVE                    32802
#define ID_FILE_OPEN                    32803
#define ID_FILE_NEW                     32804
#define ID_EDIT_PASTE                   32805
#define ID_EDIT_CUT                     32806
#define ID_EDIT_COPY                    32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1167
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
