#ifndef __appsettings_h__
#define __appsettings_h__

enum { 
  APP_BP_DRAW_MOUSE_LINE, APP_BP_DRAW_MOUSE, APP_BP_TIME_STAMP, APP_BP_SHOW_TOOLBAR,
  APP_BP_SHOW_TOOLBAR_TEXT, APP_BP_SHOW_LARGE_ICONS, APP_BP_FIX_LAYOUT,
  APP_BP_SHOW_SLIDER, APP_BP_COPY_ALL_ON_STOP, APP_BP_START_MOUSE,
  APP_BP_START_SPACE, APP_BP_KEY_CONTROL, APP_BP_WINDOW_PAUSE,
  APP_BP_CONTROL_MODE, APP_BP_COLOUR_MODE, APP_BP_KEYBOARD_MODE, APP_BP_MOUSEPOS_MODE,
  APP_BP_SPEECH_MODE, APP_BP_OUTLINE_MODE, APP_BP_PALETTE_CHANGE, APP_BP_NUMBER_DIMENSIONS,
  APP_BP_EYETRACKER_MODE, APP_BP_AUTOCALIBRATE, APP_BP_DASHER_PAUSED,
  APP_BP_GAME_MODE, APP_BP_TRAINING, APP_BP_REDRAW, APP_BP_LM_DICTIONARY, 
  APP_BP_LM_LETTER_EXCLUSION, END_OF_APP_BPS
};

enum { 
  APP_LP_ORIENTATION = END_OF_APP_BPS, APP_LP_REAL_ORIENTATION, APP_LP_MAX_BITRATE, APP_LP_FILE_ENCODING,
  APP_LP_VIEW_ID, APP_LP_LANGUAGE_MODEL_ID, APP_LP_EDIT_FONT_SIZE, APP_LP_EDIT_HEIGHT,
  APP_LP_SCREEN_WIDTH, APP_LP_SCREEN_HEIGHT, APP_LP_DASHER_FONTSIZE,
  APP_LP_UNIFORM, APP_LP_YSCALE, APP_LP_MOUSEPOSDIST, APP_LP_TRUNCATION,
  APP_LP_TRUNCATIONTYPE, APP_LP_LM_MAX_ORDER, APP_LP_LM_EXCLUSION,
  APP_LP_LM_UPDATE_EXCLUSION, APP_LP_LM_ALPHA, APP_LP_LM_BETA,
  APP_LP_LM_MIXTURE, APP_LP_MOUSE_POS_BOX, APP_LP_NORMALIZATION, APP_LP_LINE_WIDTH, 
  APP_LP_LM_WORD_ALPHA, END_OF_APP_LPS
};

enum {
  APP_SP_ALPHABET_ID = END_OF_APP_LPS, APP_SP_COLOUR_ID, APP_SP_DASHER_FONT,
  APP_SP_EDIT_FONT, APP_SP_SYSTEM_LOC, APP_SP_USER_LOC, APP_SP_GAME_TEXT_FILE,
  APP_SP_TRAIN_FILE, END_OF_APP_SPS
};

bool get_app_parameter_bool( int iParameter );
void set_app_parameter_bool( int iParameter, bool bValue );

#endif
