/* this is from part of an autogenerated file in the gtk+ distribution */

#ifndef DISABLE_VISIBILITY

#include <glib.h>

#ifdef G_HAVE_GNUC_VISIBILITY

#ifndef GTK_DISABLE_DEPRECATED
#define GTK_DISABLE_DEPRECATED
#define REENABLE_DEPRECATED
#endif

#undef dasher_gtk_text_view_add_child_at_anchor 
extern __typeof (dasher_gtk_text_view_add_child_at_anchor) dasher_gtk_text_view_add_child_at_anchor __attribute((alias("IA__dasher_gtk_text_view_add_child_at_anchor"), visibility("default")));

#undef dasher_gtk_text_view_add_child_in_window 
extern __typeof (dasher_gtk_text_view_add_child_in_window) dasher_gtk_text_view_add_child_in_window __attribute((alias("IA__dasher_gtk_text_view_add_child_in_window"), visibility("default")));

#undef dasher_gtk_text_view_backward_display_line 
extern __typeof (dasher_gtk_text_view_backward_display_line) dasher_gtk_text_view_backward_display_line __attribute((alias("IA__dasher_gtk_text_view_backward_display_line"), visibility("default")));

#undef dasher_gtk_text_view_backward_display_line_start 
extern __typeof (dasher_gtk_text_view_backward_display_line_start) dasher_gtk_text_view_backward_display_line_start __attribute((alias("IA__dasher_gtk_text_view_backward_display_line_start"), visibility("default")));

#undef dasher_gtk_text_view_buffer_to_window_coords 
extern __typeof (dasher_gtk_text_view_buffer_to_window_coords) dasher_gtk_text_view_buffer_to_window_coords __attribute((alias("IA__dasher_gtk_text_view_buffer_to_window_coords"), visibility("default")));

#undef dasher_gtk_text_view_forward_display_line 
extern __typeof (dasher_gtk_text_view_forward_display_line) dasher_gtk_text_view_forward_display_line __attribute((alias("IA__dasher_gtk_text_view_forward_display_line"), visibility("default")));

#undef dasher_gtk_text_view_forward_display_line_end 
extern __typeof (dasher_gtk_text_view_forward_display_line_end) dasher_gtk_text_view_forward_display_line_end __attribute((alias("IA__dasher_gtk_text_view_forward_display_line_end"), visibility("default")));

#undef dasher_gtk_text_view_get_accepts_tab 
extern __typeof (dasher_gtk_text_view_get_accepts_tab) dasher_gtk_text_view_get_accepts_tab __attribute((alias("IA__dasher_gtk_text_view_get_accepts_tab"), visibility("default")));

#undef dasher_gtk_text_view_get_border_window_size 
extern __typeof (dasher_gtk_text_view_get_border_window_size) dasher_gtk_text_view_get_border_window_size __attribute((alias("IA__dasher_gtk_text_view_get_border_window_size"), visibility("default")));

#undef dasher_gtk_text_view_get_buffer 
extern __typeof (dasher_gtk_text_view_get_buffer) dasher_gtk_text_view_get_buffer __attribute((alias("IA__dasher_gtk_text_view_get_buffer"), visibility("default")));

#undef dasher_gtk_text_view_get_cursor_visible 
extern __typeof (dasher_gtk_text_view_get_cursor_visible) dasher_gtk_text_view_get_cursor_visible __attribute((alias("IA__dasher_gtk_text_view_get_cursor_visible"), visibility("default")));

#undef dasher_gtk_text_view_get_default_attributes 
extern __typeof (dasher_gtk_text_view_get_default_attributes) dasher_gtk_text_view_get_default_attributes __attribute((alias("IA__dasher_gtk_text_view_get_default_attributes"), visibility("default")));

#undef dasher_gtk_text_view_get_editable 
extern __typeof (dasher_gtk_text_view_get_editable) dasher_gtk_text_view_get_editable __attribute((alias("IA__dasher_gtk_text_view_get_editable"), visibility("default")));

#undef dasher_gtk_text_view_get_indent 
extern __typeof (dasher_gtk_text_view_get_indent) dasher_gtk_text_view_get_indent __attribute((alias("IA__dasher_gtk_text_view_get_indent"), visibility("default")));

#undef dasher_gtk_text_view_get_iter_at_location 
extern __typeof (dasher_gtk_text_view_get_iter_at_location) dasher_gtk_text_view_get_iter_at_location __attribute((alias("IA__dasher_gtk_text_view_get_iter_at_location"), visibility("default")));

#undef dasher_gtk_text_view_get_iter_at_position 
extern __typeof (dasher_gtk_text_view_get_iter_at_position) dasher_gtk_text_view_get_iter_at_position __attribute((alias("IA__dasher_gtk_text_view_get_iter_at_position"), visibility("default")));

#undef dasher_gtk_text_view_get_iter_location 
extern __typeof (dasher_gtk_text_view_get_iter_location) dasher_gtk_text_view_get_iter_location __attribute((alias("IA__dasher_gtk_text_view_get_iter_location"), visibility("default")));

#undef dasher_gtk_text_view_get_justification 
extern __typeof (dasher_gtk_text_view_get_justification) dasher_gtk_text_view_get_justification __attribute((alias("IA__dasher_gtk_text_view_get_justification"), visibility("default")));

#undef dasher_gtk_text_view_get_left_margin 
extern __typeof (dasher_gtk_text_view_get_left_margin) dasher_gtk_text_view_get_left_margin __attribute((alias("IA__dasher_gtk_text_view_get_left_margin"), visibility("default")));

#undef dasher_gtk_text_view_get_line_at_y 
extern __typeof (dasher_gtk_text_view_get_line_at_y) dasher_gtk_text_view_get_line_at_y __attribute((alias("IA__dasher_gtk_text_view_get_line_at_y"), visibility("default")));

#undef dasher_gtk_text_view_get_line_yrange 
extern __typeof (dasher_gtk_text_view_get_line_yrange) dasher_gtk_text_view_get_line_yrange __attribute((alias("IA__dasher_gtk_text_view_get_line_yrange"), visibility("default")));

#undef dasher_gtk_text_view_get_overwrite 
extern __typeof (dasher_gtk_text_view_get_overwrite) dasher_gtk_text_view_get_overwrite __attribute((alias("IA__dasher_gtk_text_view_get_overwrite"), visibility("default")));

#undef dasher_gtk_text_view_get_pixels_above_lines 
extern __typeof (dasher_gtk_text_view_get_pixels_above_lines) dasher_gtk_text_view_get_pixels_above_lines __attribute((alias("IA__dasher_gtk_text_view_get_pixels_above_lines"), visibility("default")));

#undef dasher_gtk_text_view_get_pixels_below_lines 
extern __typeof (dasher_gtk_text_view_get_pixels_below_lines) dasher_gtk_text_view_get_pixels_below_lines __attribute((alias("IA__dasher_gtk_text_view_get_pixels_below_lines"), visibility("default")));

#undef dasher_gtk_text_view_get_pixels_inside_wrap 
extern __typeof (dasher_gtk_text_view_get_pixels_inside_wrap) dasher_gtk_text_view_get_pixels_inside_wrap __attribute((alias("IA__dasher_gtk_text_view_get_pixels_inside_wrap"), visibility("default")));

#undef dasher_gtk_text_view_get_right_margin 
extern __typeof (dasher_gtk_text_view_get_right_margin) dasher_gtk_text_view_get_right_margin __attribute((alias("IA__dasher_gtk_text_view_get_right_margin"), visibility("default")));

#undef dasher_gtk_text_view_get_tabs 
extern __typeof (dasher_gtk_text_view_get_tabs) dasher_gtk_text_view_get_tabs __attribute((alias("IA__dasher_gtk_text_view_get_tabs"), visibility("default")));

#undef dasher_gtk_text_view_get_type 
extern __typeof (dasher_gtk_text_view_get_type) dasher_gtk_text_view_get_type __attribute((alias("IA__dasher_gtk_text_view_get_type"), visibility("default")));

#undef dasher_gtk_text_view_get_visible_rect 
extern __typeof (dasher_gtk_text_view_get_visible_rect) dasher_gtk_text_view_get_visible_rect __attribute((alias("IA__dasher_gtk_text_view_get_visible_rect"), visibility("default")));

#undef dasher_gtk_text_view_get_window 
extern __typeof (dasher_gtk_text_view_get_window) dasher_gtk_text_view_get_window __attribute((alias("IA__dasher_gtk_text_view_get_window"), visibility("default")));

#undef dasher_gtk_text_view_get_window_type 
extern __typeof (dasher_gtk_text_view_get_window_type) dasher_gtk_text_view_get_window_type __attribute((alias("IA__dasher_gtk_text_view_get_window_type"), visibility("default")));

#undef dasher_gtk_text_view_get_wrap_mode 
extern __typeof (dasher_gtk_text_view_get_wrap_mode) dasher_gtk_text_view_get_wrap_mode __attribute((alias("IA__dasher_gtk_text_view_get_wrap_mode"), visibility("default")));

#undef dasher_gtk_text_view_move_child 
extern __typeof (dasher_gtk_text_view_move_child) dasher_gtk_text_view_move_child __attribute((alias("IA__dasher_gtk_text_view_move_child"), visibility("default")));

#undef dasher_gtk_text_view_move_mark_onscreen 
extern __typeof (dasher_gtk_text_view_move_mark_onscreen) dasher_gtk_text_view_move_mark_onscreen __attribute((alias("IA__dasher_gtk_text_view_move_mark_onscreen"), visibility("default")));

#undef dasher_gtk_text_view_move_visually 
extern __typeof (dasher_gtk_text_view_move_visually) dasher_gtk_text_view_move_visually __attribute((alias("IA__dasher_gtk_text_view_move_visually"), visibility("default")));

#undef dasher_gtk_text_view_new 
extern __typeof (dasher_gtk_text_view_new) dasher_gtk_text_view_new __attribute((alias("IA__dasher_gtk_text_view_new"), visibility("default")));

#undef dasher_gtk_text_view_new_with_buffer 
extern __typeof (dasher_gtk_text_view_new_with_buffer) dasher_gtk_text_view_new_with_buffer __attribute((alias("IA__dasher_gtk_text_view_new_with_buffer"), visibility("default")));

#undef dasher_gtk_text_view_place_cursor_onscreen 
extern __typeof (dasher_gtk_text_view_place_cursor_onscreen) dasher_gtk_text_view_place_cursor_onscreen __attribute((alias("IA__dasher_gtk_text_view_place_cursor_onscreen"), visibility("default")));

#undef dasher_gtk_text_view_scroll_mark_onscreen 
extern __typeof (dasher_gtk_text_view_scroll_mark_onscreen) dasher_gtk_text_view_scroll_mark_onscreen __attribute((alias("IA__dasher_gtk_text_view_scroll_mark_onscreen"), visibility("default")));

#undef dasher_gtk_text_view_scroll_to_iter 
extern __typeof (dasher_gtk_text_view_scroll_to_iter) dasher_gtk_text_view_scroll_to_iter __attribute((alias("IA__dasher_gtk_text_view_scroll_to_iter"), visibility("default")));

#undef dasher_gtk_text_view_scroll_to_mark 
extern __typeof (dasher_gtk_text_view_scroll_to_mark) dasher_gtk_text_view_scroll_to_mark __attribute((alias("IA__dasher_gtk_text_view_scroll_to_mark"), visibility("default")));

#undef dasher_gtk_text_view_set_accepts_tab 
extern __typeof (dasher_gtk_text_view_set_accepts_tab) dasher_gtk_text_view_set_accepts_tab __attribute((alias("IA__dasher_gtk_text_view_set_accepts_tab"), visibility("default")));

#undef dasher_gtk_text_view_set_border_window_size 
extern __typeof (dasher_gtk_text_view_set_border_window_size) dasher_gtk_text_view_set_border_window_size __attribute((alias("IA__dasher_gtk_text_view_set_border_window_size"), visibility("default")));

#undef dasher_gtk_text_view_set_buffer 
extern __typeof (dasher_gtk_text_view_set_buffer) dasher_gtk_text_view_set_buffer __attribute((alias("IA__dasher_gtk_text_view_set_buffer"), visibility("default")));

#undef dasher_gtk_text_view_set_cursor_visible 
extern __typeof (dasher_gtk_text_view_set_cursor_visible) dasher_gtk_text_view_set_cursor_visible __attribute((alias("IA__dasher_gtk_text_view_set_cursor_visible"), visibility("default")));

#undef dasher_gtk_text_view_set_editable 
extern __typeof (dasher_gtk_text_view_set_editable) dasher_gtk_text_view_set_editable __attribute((alias("IA__dasher_gtk_text_view_set_editable"), visibility("default")));

#undef dasher_gtk_text_view_set_indent 
extern __typeof (dasher_gtk_text_view_set_indent) dasher_gtk_text_view_set_indent __attribute((alias("IA__dasher_gtk_text_view_set_indent"), visibility("default")));

#undef dasher_gtk_text_view_set_justification 
extern __typeof (dasher_gtk_text_view_set_justification) dasher_gtk_text_view_set_justification __attribute((alias("IA__dasher_gtk_text_view_set_justification"), visibility("default")));

#undef dasher_gtk_text_view_set_left_margin 
extern __typeof (dasher_gtk_text_view_set_left_margin) dasher_gtk_text_view_set_left_margin __attribute((alias("IA__dasher_gtk_text_view_set_left_margin"), visibility("default")));

#undef dasher_gtk_text_view_set_overwrite 
extern __typeof (dasher_gtk_text_view_set_overwrite) dasher_gtk_text_view_set_overwrite __attribute((alias("IA__dasher_gtk_text_view_set_overwrite"), visibility("default")));

#undef dasher_gtk_text_view_set_pixels_above_lines 
extern __typeof (dasher_gtk_text_view_set_pixels_above_lines) dasher_gtk_text_view_set_pixels_above_lines __attribute((alias("IA__dasher_gtk_text_view_set_pixels_above_lines"), visibility("default")));

#undef dasher_gtk_text_view_set_pixels_below_lines 
extern __typeof (dasher_gtk_text_view_set_pixels_below_lines) dasher_gtk_text_view_set_pixels_below_lines __attribute((alias("IA__dasher_gtk_text_view_set_pixels_below_lines"), visibility("default")));

#undef dasher_gtk_text_view_set_pixels_inside_wrap 
extern __typeof (dasher_gtk_text_view_set_pixels_inside_wrap) dasher_gtk_text_view_set_pixels_inside_wrap __attribute((alias("IA__dasher_gtk_text_view_set_pixels_inside_wrap"), visibility("default")));

#undef dasher_gtk_text_view_set_right_margin 
extern __typeof (dasher_gtk_text_view_set_right_margin) dasher_gtk_text_view_set_right_margin __attribute((alias("IA__dasher_gtk_text_view_set_right_margin"), visibility("default")));

#undef dasher_gtk_text_view_set_tabs 
extern __typeof (dasher_gtk_text_view_set_tabs) dasher_gtk_text_view_set_tabs __attribute((alias("IA__dasher_gtk_text_view_set_tabs"), visibility("default")));

#undef dasher_gtk_text_view_set_wrap_mode 
extern __typeof (dasher_gtk_text_view_set_wrap_mode) dasher_gtk_text_view_set_wrap_mode __attribute((alias("IA__dasher_gtk_text_view_set_wrap_mode"), visibility("default")));

#undef dasher_gtk_text_view_starts_display_line 
extern __typeof (dasher_gtk_text_view_starts_display_line) dasher_gtk_text_view_starts_display_line __attribute((alias("IA__dasher_gtk_text_view_starts_display_line"), visibility("default")));

#undef dasher_gtk_text_view_window_to_buffer_coords 
extern __typeof (dasher_gtk_text_view_window_to_buffer_coords) dasher_gtk_text_view_window_to_buffer_coords __attribute((alias("IA__dasher_gtk_text_view_window_to_buffer_coords"), visibility("default")));

#ifdef REENABLE_DEPRECATED
#undef GTK_DISABLE_DEPRECATED
#endif

#endif /* G_HAVE_GNUC_VISIBILITY */
#endif /* DISABLE_VISIBILITY */
