#ifndef DASHER_MENUS_H
#define DASHER_MENUS_H

GtkItemFactoryEntry entries[] = {
  { "/_File",         NULL,      NULL,         0, "<Branch>" },
  { "/File/_New",     "<CTRL>N", *GtkItemFactoryCallback(select_new_file),     1, "<StockItem>", GTK_STOCK_NEW },
  { "/File/_Open...", "<CTRL>O", *GtkItemFactoryCallback(select_open_file),    1, "<StockItem>", GTK_STOCK_OPEN },
  { "/File/Save",     NULL, save_file, 0, "<StockItem>", GTK_STOCK_SAVE },
  { "/File/Save As...", NULL, select_save_file_as, 0, "<StockItem>", GTK_STOCK_SAVE_AS },
  { "/File/Append to File...", NULL, select_append_file, 0, "<Item>" },
  { "/File/sep1",     NULL,      NULL,         0, "<Separator>" },
  { "/File/Import Training Text...", NULL, select_import_file, 0, "<Item>" },
  { "/File/sepl", NULL, NULL, 0, "<Separator>" },
  { "/File/_Quit",    "<CTRL>Q", *GtkItemFactoryCallback(ask_save_before_exit), 0, "<StockItem>", GTK_STOCK_QUIT },
  { "/Edit", NULL, NULL, 0, "<Branch>" },
  { "/Edit/Cut", NULL, clipboard_cut, 0, "<StockItem>", GTK_STOCK_CUT },
  { "/Edit/Copy", NULL, clipboard_copy, 0, "<StockItem>", GTK_STOCK_COPY },
  { "/Edit/Paste", NULL, clipboard_paste, 0, "<StockItem>", GTK_STOCK_PASTE },
  { "/Edit/sepl", NULL, NULL, 0, "<Separator>" },
  { "/Edit/Copy All", NULL, clipboard_copy_all, 0, "<Item>" },
  { "/Edit/sepl", NULL, NULL, 0, "<Separator>" },
  { "/Edit/Select All", NULL, clipboard_select_all, 0, "<Item>" },
  { "/View", NULL, NULL, 0, "<Branch>" },
  { "/View/Orientation", NULL, NULL, 0, "<Branch>" },
  { "/View/Orientation/Alphabet Default", NULL, *GtkItemFactoryCallback(orientation), 1, "<RadioItem>" },
  { "/View/Orientation/sepl", NULL, NULL, 0, "<Separator>" },
  { "/View/Orientation/Left to Right", NULL, *GtkItemFactoryCallback(orientation), 3, "/View/Orientation/Alphabet Default" },
  { "/View/Orientation/Right to Left", NULL, *GtkItemFactoryCallback(orientation), 4, "/View/Orientation/Alphabet Default" },
  { "/View/Orientation/Top to Bottom", NULL, *GtkItemFactoryCallback(orientation), 5, "/View/Orientation/Alphabet Default" },
  { "/View/Orientation/Bottom to Top", NULL, *GtkItemFactoryCallback(orientation), 6, "/View/Orientation/Alphabet Default" },
  { "/View/sepl", NULL, NULL, 0, "<Separator>" },
  { "/View/Show Toolbar", NULL, *GtkItemFactoryCallback(show_toolbar), 1, "<CheckItem>" },
  { "/View/Speed Slider", NULL, *GtkItemFactoryCallback(show_slider), 1, "<CheckItem>" },
  //  { "/View/sepl", NULL, NULL, 0, "<Separator>" },
  //  { "/View/Fix Layout", NULL, NULL, 0, "<CheckItem>" },
  { "/Options", NULL, NULL, 0, "<Branch>" },
  { "/Options/Timestamp New Files", NULL, *GtkItemFactoryCallback(timestamp_files), 1, "<CheckItem>" },
  { "/Options/Copy All on Stop", NULL, *GtkItemFactoryCallback(copy_all_on_stop), 1, "<CheckItem>" },
  { "/Options/sepl", NULL, NULL, 0, "<Separator>" },
  { "/Options/Alphabet...", NULL, *GtkItemFactoryCallback(show_preferences), 1, "<Item>" },
  { "/Options/File Encoding", NULL, NULL, 0, "<Branch>" },
  { "/Options/File Encoding/User Default", NULL, *GtkItemFactoryCallback(file_encoding), 2, "<RadioItem>" },
  { "/Options/File Encoding/Alphabet Default", NULL, *GtkItemFactoryCallback(file_encoding), 1, "/Options/File Encoding/User Default" },
  { "/Options/File Encoding/Unicode UTF8", NULL, *GtkItemFactoryCallback(file_encoding), 65004, "/Options/File Encoding/User Default" },
  { "/Options/File Encoding/Unicode UTF16 (LE)", NULL, *GtkItemFactoryCallback(file_encoding), 1203, "/Options/File Encoding/User Default" },
  { "/Options/File Encoding/Unicode UTF16 (BE)", NULL, *GtkItemFactoryCallback(file_encoding), 1204, "/Options/File Encoding/User Default" },
  { "/Options/sepl", NULL, NULL, 0, "<Separator>" },
  { "/Options/Font Size", NULL, NULL, 0, "<Branch>" },
  { "/Options/Font Size/Default Fonts", NULL, *GtkItemFactoryCallback(set_dasher_fontsize), 1, "<RadioItem>" },
  { "/Options/Font Size/Large Fonts", NULL, *GtkItemFactoryCallback(set_dasher_fontsize), 2, "/Options/Font Size/Default Fonts" },
  { "/Options/Font Size/Very Large Fonts", NULL, *GtkItemFactoryCallback(set_dasher_fontsize), 4, "/Options/Font Size/Default Fonts" },
  { "/Options/Editing Font...", NULL, *GtkItemFactoryCallback(set_edit_font), 1, "<Item>" },
  { "/Options/Dasher Font...", NULL, *GtkItemFactoryCallback(set_dasher_font), 1, "<Item>" },
  { "/Options/Reset Fonts", NULL, *GtkItemFactoryCallback(reset_fonts), 1, "<Item>" },
  { "/Options/One Dimensional", NULL, *GtkItemFactoryCallback(SetDimension), 1, "<CheckItem>" },
  { "/Options/Eyetracker Mode", NULL, *GtkItemFactoryCallback(SetEyetracker), 1, "<CheckItem>" },
  { "/Options/Draw Position", NULL, *GtkItemFactoryCallback(DrawMouse), 1, "<CheckItem>" },
  { "/Options/Start on Left Mouse", NULL, *GtkItemFactoryCallback(startonleft), 1, "<CheckItem>" },
  { "/Options/Start on Space Bar", NULL, *GtkItemFactoryCallback(startonspace), 1, "<CheckItem>" },
  { "/Options/Start on Mouse Position", NULL, *GtkItemFactoryCallback(startonmousepos), 1, "<CheckItem>" },
  { "/Options/Keyboard Control", NULL, *GtkItemFactoryCallback(keycontrol), 1, "<CheckItem>" },
  { "/Options/Pause outside Window", NULL, *GtkItemFactoryCallback(windowpause), 1, "<CheckItem>" },
  { "/Options/Control Mode", NULL, *GtkItemFactoryCallback(controlmode), 1, "<CheckItem>" },
  { "/Options/Enter Text into Other Windows", NULL, *GtkItemFactoryCallback(keyboardmode), 1, "<CheckItem>" },
  { "/Help", NULL, NULL, 0, "<Branch>" },
  { "/Help/About", NULL, *GtkItemFactoryCallback(about_dasher), 0, "<Item>" }
 };

#endif
