#ifndef __event_h__
#define __event_h__

// Classes representing different event types.

#include <string>
#include "DasherTypes.h"

namespace Dasher {
  class CEvent;
  class CParameterNotificationEvent;
  class CEditEvent;
  class CScreenGeomEvent;
}

enum {
  EV_PARAM_NOTIFY = 1, EV_EDIT, EV_SCREEN_GEOM
};

/// \ingroup Core
/// @{

/// \defgroup Events Events generated by Dasher modules.
/// @{
class Dasher::CEvent {
protected:
  CEvent(int iEventType) : m_iEventType(iEventType) {}
public:
  const int m_iEventType;
};

class Dasher::CParameterNotificationEvent:public Dasher::CEvent {
public:
  CParameterNotificationEvent(int iParameter) : CEvent(EV_PARAM_NOTIFY), m_iParameter(iParameter) {
  };

  const int m_iParameter;
};

class Dasher::CEditEvent:public Dasher::CEvent {
public:
  CEditEvent(int iEditType, const std::string & sText, int iOffset)
  : CEvent(EV_EDIT), m_iEditType(iEditType), m_sText(sText), m_iOffset(iOffset) {
  };

  const int m_iEditType;
  const std::string m_sText;
  const int m_iOffset;
};

///Generated whenever the screen geometry changes: e.g. aspect ratio,
/// size, degree of nonlinearity, orientation, or generally whenever
/// values returned by Dasher2Screen/Screen2Dasher might have changed
/// (thus, any code caching such values should recompute/invalidate them)
class Dasher::CScreenGeomEvent : public Dasher::CEvent {
public:
  CScreenGeomEvent() : CEvent(EV_SCREEN_GEOM) {
  }
};
/// @}
/// @}

#endif
